name:                tweeth
version:             0.1.0.0
github:              "githubuser/tweeth"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tweeth#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- case-insensitive
- containers
- http-conduit
- lens
- mtl
- network
- network-uri
- text
- twitter-conduit
- twitter-types
- twitter-types-lens
- websockets
- wuss

library:
  source-dirs: src

executables:
  tweeth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tweeth

tests:
  tweeth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tweeth
    - hspec
